Repository Elskom/Els_kom_new, pull requests merged in 2018-06, with the labels that each got.

#55 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#57 Add base branch name to release description.
  appveyor.yml
Labels: enhancement

#58 Removed old readme.
  readme.txt
Labels: enhancement

#59 Optimized if in callbacktest plugin.
  Plugins/callbackplugins/CallbacktestForm.cs
Labels: C#, enhancement

#60 Reworked resources.
  .gitignore
  Els_kom_Core/Classes/Icons.cs
  Els_kom_Core/Classes/LoadResources.cs
  Els_kom_Core/Classes/SafeNativeMethods.cs
  Els_kom_Core/Els_kom_Core.csproj
  PCbuild/Els_kom_resources.vcxproj
  PCbuild/Els_kom_resources.vcxproj.filters
  PCbuild/pcbuild.sln
  gitbuildinfo/Program.cs
  gitbuildinfo/Properties/AssemblyInfo.cs
  gitbuildinfo/gitbuildinfo.csproj
  packbuild/Program.cs
Labels: C#, enhancement

#61 Put Els_kom version in manifest.
  Els_kom/Resources/els_kom.manifest
Labels: enhancement

#62 Hide zlib classes
  Els_kom_Core/Classes/Zlib/SupportClass.cs
  Els_kom_Core/Classes/Zlib/ZInputStream.cs
  Els_kom_Core/Classes/Zlib/ZOutputStream.cs
  Els_kom_Core/Classes/Zlib/ZStream.cs
  Els_kom_Core/Classes/Zlib/Zlib.cs
Labels: C#, enhancement

#63 Hide resource loading class.
  Els_kom_Core/Classes/LoadResources.cs
Labels: C#, enhancement

#64 Hide some more classes.
  Els_kom/Forms/Els_kom_Main_MainForm.cs
  Els_kom_Core/Classes/ExecutionManager.cs
  Els_kom_Core/Classes/KOMManager.cs
  Els_kom_Core/Controls/MainControl.cs
Labels: C#, enhancement

#66 Fixed spelling issue in changelog entries.
  Misc/NEWS/1.4.3.0/item002
Labels: enhancement

#67 Fixed icon link.
  readme.md
Labels: enhancement

#68 Add changelog to build and deployment Els_kom_new.zip file.
  appveyor.yml
  packbuild/Program.cs
Labels: C#, enhancement

#71 Fixed reloading settings file when it does not need reloaded.
  Els_kom_Core/Classes/XMLObject.cs
  Els_kom_Core/Controls/MainControl.cs
Labels: C#, enhancement

#72 Fixed changelog config.
  Misc/NEWS/news.master
Labels: C#, enhancement

#73 Changed the About Window Description.
  Els_kom/Resources/els_kom.ico
  Els_kom_Core/Controls/AboutControl.Designer.cs
  Els_kom_Core/Controls/MainControl.Designer.cs
  Els_kom_Core/Controls/SettingsControl.Designer.cs
  Els_kom_Core/Els_kom_Core.csproj
Labels: C#, enhancement

#74 Update Icon image.
  els_kom.png
Labels: enhancement

#78 Updated Readme.
  readme.md
Labels: enhancement

#77 Fixed CPU usage.
  Els_kom_Core/Classes/ExecutionManager.cs
  Els_kom_Core/Controls/MainControl.cs
Labels: C#, bug, enhancement

#79 Removed zlib files and linked zlib source files.
  .gitignore
  Els_kom_Core/Classes/Zlib/Adler32.cs
  Els_kom_Core/Classes/Zlib/Deflate.cs
  Els_kom_Core/Classes/Zlib/InfBlocks.cs
  Els_kom_Core/Classes/Zlib/InfCodes.cs
  Els_kom_Core/Classes/Zlib/InfTree.cs
  Els_kom_Core/Classes/Zlib/Inflate.cs
  Els_kom_Core/Classes/Zlib/StaticTree.cs
  Els_kom_Core/Classes/Zlib/SupportClass.cs
  Els_kom_Core/Classes/Zlib/Tree.cs
  Els_kom_Core/Classes/Zlib/ZInputStream.cs
  Els_kom_Core/Classes/Zlib/ZOutputStream.cs
  Els_kom_Core/Classes/Zlib/ZStream.cs
  Els_kom_Core/Classes/Zlib/ZStreamException.cs
  Els_kom_Core/Classes/Zlib/Zlib.cs
  Els_kom_Core/Els_kom_Core.csproj
  appveyor.yml
  externals/README.md
  readme.md
Labels: C#, enhancement
