Repository Elskom/Els_kom_new, pull requests merged in 2018-07, with the labels that each got.

#80 Added crash report issue template.
  .github/ISSUE_TEMPLATE/crash-report.md
Labels: enhancement

#81 Fixed project files.
  Els_kom/Els_kom.csproj
  Els_kom_Core/Els_kom_Core.csproj
  Plugins/callbacktest_plugin.csproj
  Plugins/komv2_plugin.csproj
  Plugins/komv3_plugin.csproj
  Plugins/komv4_plugin.csproj
Labels: C#, enhancement

#82 Cat girls are life patch 1
  appveyor.yml
  readme.md
Labels: enhancement

#83 Inform users the contents of zip files generated.
  packbuild/Program.cs
Labels: C#, enhancement

#84 Start on changing badges an providing vs2017 & preview specific ones.
  readme.md
Labels: enhancement

#76 Added crc.xml converter.
  .gitignore
  Els_kom/Els_kom.csproj
  Els_kom/Els_kom_Main.cs
  Els_kom/Forms/Els_kom_Main_AboutForm.cs
  Els_kom/Forms/Els_kom_Main_MainForm.cs
  Els_kom/Forms/Els_kom_Main_SettingsForm.cs
  Els_kom/Properties/AssemblyInfo.cs
  Els_kom/Resources/Els_kom.rc
  Els_kom/Resources/VP_Trans.icns
  Els_kom/Resources/VP_Trans.ico
  Els_kom/Resources/YR.icns
  Els_kom/Resources/YR.ico
  Els_kom/Resources/els_kom.icns
  Els_kom/Resources/els_kom.ico
  Els_kom_Core/Classes/AssemblyExtensions.cs
  Els_kom_Core/Classes/GenericPluginLoader.cs
  Els_kom_Core/Classes/Icons.cs
  Els_kom_Core/Classes/KOMStream.cs
  Els_kom_Core/Classes/MiniDump.cs
  Els_kom_Core/Classes/ZlibHelper.cs
  Els_kom_Core/Controls/SettingsControl.Designer.cs
  Els_kom_Core/Els_kom_Core.csproj
  Els_kom_Core/Properties/AssemblyInfo.cs
  Els_kom_Core/interfaces/IKomPlugin.cs
  Misc/NEWS/1.4.9.8/item028
  Misc/NEWS/1.4.9.8/item029
  Misc/NEWS/1.4.9.8/item030
  PCbuild/Core.props
  PCbuild/Main.props
  PCbuild/SharedAssemblyInfo.cs
  PCbuild/pcbuild.sln
  PCbuild/plugins.props
  Plugins/README.md
  Plugins/callbackplugins/CallbacktestForm.Designer.cs
  Plugins/callbackplugins/CallbacktestForm.cs
  Plugins/callbackplugins/Callbacktest_plugin.cs
  Plugins/callbackplugins/Properties/AssemblyInfo.cs
  Plugins/callbacktest_plugin.csproj
  Plugins/komplugins/KOMStreamExtension.cs
  Plugins/komplugins/Komv2_plugin.cs
  Plugins/komplugins/Komv3_plugin.cs
  Plugins/komplugins/Komv4_plugin.cs
  Plugins/komplugins/Properties/AssemblyInfo.cs
  Plugins/komv2_plugin.csproj
  Plugins/komv3_plugin.csproj
  Plugins/komv4_plugin.csproj
  appveyor.yml
  packbuild/Program.cs
  packbuild/Properties/AssemblyInfo.cs
  packbuild/packbuild.csproj
  readme.md
Labels: C#, enhancement

#86 Changed crc.xml updater.
  Els_kom_Core/Classes/KOMStream.cs
  Els_kom_Core/interfaces/IKomPlugin.cs
  Misc/NEWS/1.4.9.8/item030
Labels: C#, enhancement

#91 Fixed crash on new Els_kom users.
  Els_kom_Core/Classes/XMLObject.cs
  Els_kom_Core/Controls/MainControl.cs
  Misc/NEWS/1.4.9.8/item031
  appveyor.yml
Labels: C#, bug, enhancement

#92 Include AppVeyor build image name in release zip files.
  appveyor.yml
Labels: enhancement

#93 Add 64-bit build configuration.
  Els_kom/Els_kom.csproj
  Els_kom/Els_kom_Main.cs
  Misc/NEWS/1.4.9.8/item032
  PCbuild/Core.props
  PCbuild/Main.props
  PCbuild/pcbuild.sln
  appveyor.yml
Labels: C#, enhancement

#94 Update readme to reflect the new 64-bit build configuration.
  readme.md
Labels: enhancement

#95 Upload 64-bit builds to Releases as well.
  appveyor.yml
Labels: enhancement

#96 Only build newsmake if git pulled changes.
  appveyor.yml
Labels: enhancement

#97 Update readme.
  .gitattributes
  appveyor-deploy.ps1
  appveyor.yml
  package-release.cmd
  readme.md
  update-newsmake.ps1
Labels: enhancement

#98 Mention git in readne.
  readme.md
Labels: enhancement
